name: ci

on: [ push, pull_request ]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/simulatan/semesterprojekt-server
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},
            type=sha,
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: 17
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Gradle Project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -Dquarkus.package.type=native

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: {context}/src/main/docker/Dockerfile.native
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha